<?php


class Country_m extends MY_Model
{
	protected $table = "country";
	protected $primaryKey = "id";
	const CREATED_AT = NULL;
	const UPDATED_AT = NULL;

	const COUNTRY_OTHER = 9999;

	public $last_insert_id;

	public function insert($attributes, $runValidation = true)
	{
		$name = trim($attributes['name']);
		$model = $this->findOne(['name' => $name]);
		if ($model) {
			$this->last_insert_id = $model->id;
			return true;
		}
		$id = $this->find()->select_max('id')
			->where('id <', Country_m::COUNTRY_OTHER)
			->get()->row();
		if ($id) {
			$id = $id->id + 1;
		}
		$attributes['id'] = $id;
		$this->last_insert_id = $id;
		return parent::insert($attributes, $runValidation); // TODO: Change the autogenerated stub
	}
}
